import './globals.css'

import { Suspense } from 'react'
import type { Metadata } from 'next'

import { ConvexClientProvider } from '@/providers/convex-client-provider'
import { Toaster } from '@/components/ui/sonner'
import ModalProvider from '@/providers/modal-provider'
import Loading from '@/components/auth/loading'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<link rel='icon' href='./favicon.ico' />
			<body className={'font-Inter '}>
				<Suspense fallback={<Loading />}>
					<ConvexClientProvider>
						<Toaster />
						<ModalProvider />
						{children}
					</ConvexClientProvider>
				</Suspense>
			</body>
		</html>
	)
}
